/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as IndexRouteImport } from './pages/index'
import { Route as SettingsAppearanceRouteImport } from './pages/settings/appearance'
import { Route as SettingsGeneralRouteImport } from './pages/settings/general'
import { Route as SettingsKeyboardShortcutsRouteImport } from './pages/settings/keyboard-shortcuts'
import { Route as SettingsProvidersRouteImport } from './pages/settings/providers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/settings/appearance',
  path: '/settings/appearance',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/settings/general',
  path: '/settings/general',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsKeyboardShortcutsRoute =
  SettingsKeyboardShortcutsRouteImport.update({
    id: '/settings/keyboard-shortcuts',
    path: '/settings/keyboard-shortcuts',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: '/settings/providers',
  path: '/settings/providers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/keyboard-shortcuts': typeof SettingsKeyboardShortcutsRoute
  '/settings/providers': typeof SettingsProvidersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/keyboard-shortcuts': typeof SettingsKeyboardShortcutsRoute
  '/settings/providers': typeof SettingsProvidersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/keyboard-shortcuts': typeof SettingsKeyboardShortcutsRoute
  '/settings/providers': typeof SettingsProvidersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings/appearance'
    | '/settings/general'
    | '/settings/keyboard-shortcuts'
    | '/settings/providers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings/appearance'
    | '/settings/general'
    | '/settings/keyboard-shortcuts'
    | '/settings/providers'
  id:
    | '__root__'
    | '/'
    | '/settings/appearance'
    | '/settings/general'
    | '/settings/keyboard-shortcuts'
    | '/settings/providers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsKeyboardShortcutsRoute: typeof SettingsKeyboardShortcutsRoute
  SettingsProvidersRoute: typeof SettingsProvidersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/settings/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/settings/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/keyboard-shortcuts': {
      id: '/settings/keyboard-shortcuts'
      path: '/settings/keyboard-shortcuts'
      fullPath: '/settings/keyboard-shortcuts'
      preLoaderRoute: typeof SettingsKeyboardShortcutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/providers': {
      id: '/settings/providers'
      path: '/settings/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof SettingsProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsKeyboardShortcutsRoute: SettingsKeyboardShortcutsRoute,
  SettingsProvidersRoute: SettingsProvidersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
